### ISSUE TITLE
How should semiologies be combined?

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#8] opened 2020-03-23 20:58 UTC

**Comment by thenineteen** [comment] 2020-03-27 13:00
> Why would you want to do this?
because you previously noted:
>The problem with this is that some positive numbers will be mapped to 0 


>So you think we should just add the percentages and rescale again?
probably - but also try "raw" output that you wanted and see the difference?

**Comment by fepegar** [comment] 2020-03-27 14:16
Yeah but I also said: "But I guess that never happens, so this can be ignored".

Anyway, let's try to make it work again with single semiologies and then we'll think about how to combine them.

**Comment by thenineteen** [comment] 2020-05-06 15:05
what is the current method being used, 50:50 "equal weights" method?



> 1. "equal weights" method:

**Comment by fepegar** [comment] 2020-05-07 19:53
Can you define specifically what the "equal weights" method is and why you think my implementation is wrong, as you said this morning?

**Comment by fepegar** [comment] 2020-05-13 15:04
Here's some code that might clarify things. Note that I modified scores for semiologies **B** and **C** with respect to the previous table in this issue.

```python
In [1]: from mega_analysis.semiology import get_df_from_dicts, normalise_semiologies_df, combine_semiologies_df
   ...:
   ...: dicts = {
   ...:     'A': dict(X=0, Y=1, Z=1000),
   ...:     'B': dict(X=2, Y=1, Z=0),
   ...:     'C': dict(X=50, Y=50, Z=0),
   ...:     'D': dict(X=0, Y=12, Z=13),
   ...:     'E': dict(X=0, Y=0.1, Z=100),
   ...: }
   ...:
   ...: df = get_df_from_dicts(dicts)
   ...: df
Out[1]:
            X     Y     Z
Semiology
A           0   1.0  1000
B           2   1.0     0
C          50  50.0     0
D           0  12.0    13
E           0   0.1   100

In [2]: normalised_df = normalise_semiologies_df(df)
   ...: normalised_df
Out[2]:
               X           Y      Z
Semiology
A            0.0    0.100000  100.0
B          100.0   50.000000    0.0
C          100.0  100.000000    0.0
D            0.0   92.307692  100.0
E            0.0    0.100000  100.0

In [3]: combined_df = normalised_df.sum()
   ...: combined_df
Out[3]:
X    200.000000
Y    242.507692
Z    300.000000
dtype: float64

In [4]: combined_normalised_df = combined_df / combined_df.max() * 100
   ...: combined_normalised_df
Out[4]:
X     66.666667
Y     80.835897
Z    100.000000
dtype: float64
```

And with the first two semiologies only:

```python
In [1]: from mega_analysis.semiology import get_df_from_dicts, normalise_semiologies_df, combine_semiologies_df
   ...:
   ...: dicts = {
   ...:     'A': dict(X=0, Y=1, Z=1000),
   ...:     'B': dict(X=2, Y=1, Z=0),
   ...: }
   ...:
   ...: df = get_df_from_dicts(dicts)
   ...: df
Out[1]:
           X  Y     Z
Semiology
A          0  1  1000
B          2  1     0

In [2]: normalised_df = normalise_semiologies_df(df)
   ...: normalised_df
Out[2]:
               X     Y      Z
Semiology
A            0.0   0.1  100.0
B          100.0  50.0    0.0

In [3]: combined_df = normalised_df.sum()
   ...: combined_df
Out[3]:
X    100.0
Y     50.1
Z    100.0
dtype: float64

In [4]: combined_normalised_df = combined_df / combined_df.max() * 100
   ...: combined_normalised_df
Out[4]:
X    100.0
Y     50.1
Z    100.0
dtype: float64
```

**Comment by thenineteen** [comment] 2020-05-14 13:41
Thanks

I see what's happening here

there is a bias introduced inherently over weighing those semiologies with a more even distribution of localisations. what do I mean by this?  

```
           X  Y     Z
Semiology
A          0  1  1000
B          2  1     0
```

**Comment by thenineteen** [comment] 2020-05-14 13:50
instead, what we need is something more akin to a softmax probabilistic treatment of each individual raw semiology.

Say these are the raw data:
```
           X  Y     Z
Semiology
A          0  1  1000
B          2  2     2
```


softmax:

```           
           X  Y     Z
Semiology
A          0  0.01  0.99
B          0.33  0.33     0.33

```



now combine:

```
           X  Y     Z
          0.33  0.34     1.32

```



and softmax again:

```
           X  Y     Z
          0.24  0.25   0.51

```

**Comment by fepegar** [comment] 2020-05-14 14:49
Can you provide some code and results of that?

**Comment by thenineteen** [comment] 2020-05-19 12:38
equal weights methods:


  | X | Y | Z
-- | -- | -- | --
0.0 | 0.100000 | 100.0
100.0 | 50.000000 | 0.0
100.0 | 100.000000 | 0.0
0.0 | 92.307692 | 100.0
0.0 | 0.100000 | 100.0

**Comment by thenineteen** [comment] 2020-05-19 12:44
concretely: 
the value of Y is reduced in softmax version (scale by 200 for comparison)

current method:
X 66
Y 80
Z 100

softmax scaled up by 200:
X 66
Y 33
Z 100

**Comment by thenineteen** [comment] 2020-05-19 12:56
note that the parameters of the MinMaxScaler called within **normalise_semiologies_df** were changed:

```
def normalise_semiologies_df(semiologies_df: pd.DataFrame) -> pd.DataFrame:
    table = np.array(semiologies_df)
    data = table.T
    scaler = MinMaxScaler((0, 1))
    scaler.fit(data)
    normalised = scaler.transform(data).T
    normalised_df = pd.DataFrame(
        normalised,
        columns=semiologies_df.columns,
        index=semiologies_df.index,
    )
    return normalised_df
```

I suggest we use 0 to 1 (or 1 to 100) and not ZERO to 100. 


![softmax SVT](https://user-images.githubusercontent.com/10786099/82328971-80bbd300-99d8-11ea-8366-7e96a3bcfe68.jpg)

**Comment by thenineteen** [comment] 2020-05-19 13:19
and in case you want to also see the first two semiologies only:

top part is reproducing your example above, and bottom part is using the 0,1 minmaxscaler followed by softmax:

![image](https://user-images.githubusercontent.com/10786099/82331227-bf9f5800-99db-11ea-8a1b-e0b3bb21b3cc.png)

**Comment by thenineteen** [comment] 2020-05-19 13:20
in conclusion: the softmax gives a more graded distribution, and all values add up to 1.

i.e. if the Q is: patient with semiology A and B, where are the likely EZ? then this goes further in asnwering the Q.

**Comment by thenineteen** [comment] 2020-05-19 13:21
`
![image](https://user-images.githubusercontent.com/10786099/82331413-ff663f80-99db-11ea-9ea7-7c25edb2a84b.png)
`

**Comment by fepegar** [comment] 2020-05-19 17:19
> what's the best way and place to upload the jupyter notebook? resources?

You can use [Google Colab](https://colab.research.google.com/) to share an executable notebook. Probably not a good idea to start adding notebooks to the repo, specially because they don't work well with git.

Thanks for the examples. Please stick to PNG (not JPEG) for screenshots (https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/8#issuecomment-630798341 is hard to read) or, even better, paste the code directly in your comment so that I can copy & paste it if I want to run it too. Also, it's quite hard to see the effect of softmax on the table because of the scientific notation.

I think it'd make it a bit easier to imagine if the final values are scaled between 0 and 1, or 0 and 100, because the colormap will be rescaled to have whatever scale the scores have anyway.

The question is: how do we know if the technique we choose is a good of representation of the data we have? Do you think asking Aiden for advice wouldn't be a good idea?

**Comment by thenineteen** [comment] 2020-07-02 10:42
> The question is: how do we know if the technique we choose is a good of representation of the data we have? Do you think asking Aiden for advice wouldn't be a good idea?

by validating it using out of database seizure free cases - like the 14 I already did. If this was an option as in #19 then I could run them with and without softmax 0 to 1 option and see which works best...

**Comment by fepegar** [comment] 2020-07-02 12:23
You didn't follow up on the discussion about e.g. softmax after my comment on the 19th of May: https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/8#issuecomment-630961480

With softmax, scores for each semiology don't have a maximum of 100, although I guess they could be scaled up to achieve this. Another issue is that at the moment having a semiology with data points (0, 1, 2) is the same as (0, 50, 100). Softmax turns these into (0.1, 0.2, 0.7) and (0, 0, 1).

**Comment by thenineteen** [comment] 2020-07-02 16:01
| X | Y | Z
-- | -- | -- | --
0.0 | 1.0 | 1000.0
2.0 | 1.0 | 0.0
50.0 | 50.0 | 0.0
0.0 | 12.0 | 13.0
0.0 | 0.1 | 100.0

**Comment by fepegar** [comment] 2020-07-02 16:02
I don't know what you want to say with that table.

**Comment by thenineteen** [comment] 2020-07-02 16:07
> note that the parameters of the MinMaxScaler called within **normalise_semiologies_df** were changed:
> 
> ```
> def normalise_semiologies_df(semiologies_df: pd.DataFrame) -> pd.DataFrame:
>     table = np.array(semiologies_df)
>     data = table.T
>     scaler = MinMaxScaler((0, 1))
>     scaler.fit(data)
>     normalised = scaler.transform(data).T
>     normalised_df = pd.DataFrame(
>         normalised,
>         columns=semiologies_df.columns,
>         index=semiologies_df.index,
>     )
>     return normalised_df
> ```
> 
> I suggest we use 0 to 1 (or 1 to 100) and not ZERO to 100 as flattens to zero much more easily.
> 
> ![softmax SVT](https://user-images.githubusercontent.com/10786099/82328971-80bbd300-99d8-11ea-8366-7e96a3bcfe68.jpg)

the issue you quote regarding the figures will be fixed by 

1. the above (note 0 to 1)
2. when we use proportions (#118 ) rather than raw numbers, as these will be between 0 and 1, akin to a probability per semiology, then combining these as a softmax.

**Comment by fepegar** [comment] 2020-07-02 16:20
Please don't delete my comments.

**Comment by fepegar** [comment] 2020-07-02 16:22
> Please don't delete my comments.

Like, never ever.

**Comment by thenineteen** [comment] 2020-07-02 17:45
your comment was on a table which was pasted and posted by accident. The table was deleted as was the comment referring to it as otherwise reading through this would become even more confusing than it already is

**Comment by fepegar** [comment] 2020-07-02 17:53
I know, still not right to delete someone else's comment. I think everyone would agree on that.

**Comment by thenineteen** [comment] 2020-07-02 18:03
it was relevant yes, but given I know my comment was an unrelated table by accidet, then I think you must trust me not to delete comments at a whim

**Comment by thenineteen** [comment] 2020-10-25 09:49
I'm going to need an implementation of this softmax version to combine semiologies for clinical validation - do you think  you can create an extra option please which toggles combining semiology methods between the current version and softmax version I suggested above?

**Comment by fepegar** [comment] 2020-10-27 17:47
As I said in https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/8#issuecomment-652973996, softmax sets a lot of number to 0.

Softmax:

<img width="1392" alt="Screen Shot 2020-10-27 at 17 43 46" src="https://user-images.githubusercontent.com/12688084/97341050-7ac9f800-187c-11eb-9df7-3eda47a9593f.png">

Minmax:

![Uploading Screen Shot 2020-10-27 at 17.47.07.png…]()

**Comment by thenineteen** [comment] 2020-11-03 16:03
FYI

spoke with Tim Stone and Prof Norman Williams (Data Clinic. WEISS).

Agree proportions could be useful and could use either binomial proportions CI or bootstrapping. Bootstrapping CI will be problematic for low data semiologies and structures, and given the distributions from sankey, a binomial proportions one is suitable.

Tim suggests that the current combination of semiology over emphasises the whales - he thinks a better technique to normalising, even to softmax, would be a log x +1 (even using base 2)

I explained my thoughts about how to do CI per semiology per structure - 8 regions as per Sankey. the netrail point would be a naive baseline of 1/8 = 12.5%. CI straddling this mean the semiology doesn't particularly localise to that area. They agreed this is sound and works.

Similarly for lateralisation: 50% as baseline. 

Also agreed that these would be forrest plots and no summary statistic could be ascertained.

**Closed** 2020-11-06 00:53 UTC
Labels: combine semiologies, mega_analysis, slicer
